application: gistrss-hrd

version: pygments
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /favicon.ico
  static_files: media/favicon.ico
  upload: media/favicon.ico
  
- url: /robots.txt
  static_files: media/robots.txt
  upload: media/robots.txt
  
- url: /media
  static_dir: media
   
- url: /.*
  script: main.app

libraries:
- name: webapp2
  version: "2.5.2"

- name: jinja2
  version: latest
